---
- name: clone repo
  git:
    repo: "{{ deploy_laravel_repo }}"
    dest: "{{ deploy_laravel_dest }}/{{ deploy_laravel_app }}"
    force: yes
    update: yes

- name: composer install
  composer:
    command: install
    working_dir: "{{ deploy_laravel_dest }}/{{ deploy_laravel_app }}"
    no_dev: "{{ deploy_laravel_no_dev }}"

- name: copy .env.example to a temporary file
  shell: >
    cp .env.example .env.temp
  args:
    chdir: "{{ deploy_laravel_dest }}/{{ deploy_laravel_app }}"

- name: set variables in .env
  lineinfile:
    path: "{{ deploy_laravel_dest }}/{{ deploy_laravel_app }}/.env.temp"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^APP_ENV=', line: "APP_ENV={{ deploy_laravel_env }}" }
    - { regexp: '^APP_DEBUG=', line: "APP_DEBUG=false" }
    - { regexp: '^APP_URL=', line: "APP_URL={{ deploy_laravel_protocol }}://{{ deploy_laravel_domain }}" }
    - { regexp: '^DB_HOST=', line: "DB_HOST={{ deploy_laravel_dbhost }}" }
    - { regexp: '^DB_DATABASE=', line: "DB_DATABASE={{ deploy_laravel_dbname }}" }
    - { regexp: '^DB_USERNAME=', line: "DB_USERNAME={{ deploy_laravel_dbuser }}" }

- name: set password from file
  lineinfile:
    path: "{{ deploy_laravel_dest }}/{{ deploy_laravel_app }}/.env.temp"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^DB_PASSWORD=', line: "DB_PASSWORD='{{ lookup('file', deploy_laravel_dbpass_file) }}'" }
  when: deploy_laravel_dbpass_from_file 

- name: set password from variable
  lineinfile:
    path: "{{ deploy_laravel_dest }}/{{ deploy_laravel_app }}/.env.temp"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^DB_PASSWORD=', line: "DB_PASSWORD='{{ deploy_laravel_dbpass }}'" }
  when: not deploy_laravel_dbpass_from_file 

- name: move .env.temp to production
  shell: >
    mv .env.temp .env
  args:
    chdir: "{{ deploy_laravel_dest }}/{{ deploy_laravel_app }}"

- name: key artisan
  shell: php artisan key:generate
  args:
    chdir: "{{ deploy_laravel_dest }}/{{ deploy_laravel_app }}"

- name: database migration
  shell: php artisan migrate --force 
  args:
    chdir: "{{ deploy_laravel_dest }}/{{ deploy_laravel_app }}"

- name: virtualhost.conf
  template:
    src: templates/virtualhost.conf
    dest: "/etc/apache2/sites-available/{{ deploy_laravel_domain }}.conf"

- name: owner www-data
  file:
    path: "{{ deploy_laravel_dest }}/{{ deploy_laravel_app }}"
    state: directory
    owner: www-data
    group: www-data
    recurse: yes

- name: active virtualhost
  shell: a2ensite "{{ deploy_laravel_domain }}"
  args:
    creates: "/etc/apache2/sites-enabled/{{ deploy_laravel_domain }}.conf"
  notify:
    restart apache2
