- name: Install supervisor
  apt:
    name: "supervisor"
    update_cache: yes

- name: supervisor.j2
  template:
    src: templates/supervisor.j2
    dest: "/etc/supervisor/conf.d/{{ deploy_laravel_domain.split('.')[0] | lower }}_queue_worker_default.conf"
  tags:
    - deploy_laravel

- name: supervisorctl reread
  shell: supervisorctl reread

- name: supervisorctl update
  shell: supervisorctl update

- name: supervisorctl restart all
  shell: supervisorctl restart all